feat-price
AddNiI/Final_Project_2team_Minimal pull request #3
Opened 2023-12-05 11:43 UTC by AddNiI

2023-12-06 22:58 UTC, marianaD4 requested changes

2023-12-06 22:58 UTC, marianaD4 commented on scss/components/_price.scss
> +        width: 704px;
потрібно використовувати загальний контейнер

2023-12-06 22:58 UTC, marianaD4 commented on scss/components/_price.scss
> +        color: var(--Blue-font, #0A224A);
var?
використовуємо змінні, які мають бути прописані у файлі

2023-12-07 14:40 UTC, AddNiI commented on scss/components/_price.scss
> +        width: 704px;
це він і є

2023-12-26 00:06 UTC, marianaD4 reviewed
Немає анімації на ховер

2023-12-26 00:06 UTC, marianaD4 commented on scss/components/_price.scss
> +        color: #0A224A;
для кольору використовуємо змінні

2023-12-26 00:06 UTC, marianaD4 commented on scss/components/_price.scss
> +        color: #0A224A;
для кольору використовуємо змінні

2023-12-26 00:06 UTC, marianaD4 commented on scss/components/_price.scss
> +    width: 343px;
використовуємо контейнер

2023-12-26 00:06 UTC, marianaD4 commented on scss/components/_price.scss
> +        width: 704px;
використовуємо контейнер

2023-12-26 00:06 UTC, marianaD4 commented on scss/components/_price.scss
> +        width: 1096px;
використовуємо контейнер

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +        color: var(--Blue-font, #0A224A);
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +        color: #0A224A;
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +        color: #0A224A;
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +    width: 343px;
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +        width: 704px;
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_price.scss
> +        width: 1096px;
?

2024-01-09 09:59 UTC, marianaD4 requested changes

2024-01-09 09:59 UTC, marianaD4 commented on scss/components/_price.scss
> +    width: 343px;
Тут є контейнер викорстовуємо його, а не фіксовану ширину https://github.com/AddNiI/Final_Project_2team_Minimal/blob/feat-price/SCSS/components/_global.scss

2024-01-09 09:59 UTC, marianaD4 commented on scss/components/_price.scss
> +        color: #0A224A;
https://sass-lang.com/documentation/variables/

2024-01-09 09:59 UTC, marianaD4 commented on scss/components/_price.scss
> +        color: #0A224A;
https://sass-lang.com/documentation/variables/

2024-01-09 09:59 UTC, marianaD4 commented on scss/components/_price.scss
> +        width: 704px;
https://github.com/AddNiI/Final_Project_2team_Minimal/blob/feat-price/SCSS/components/_global.scss

2024-01-09 09:59 UTC, marianaD4 commented on scss/components/_price.scss
> +        width: 1096px;
https://github.com/AddNiI/Final_Project_2team_Minimal/blob/feat-price/SCSS/components/_global.scss

2024-01-09 18:02 UTC, merged