Feat bestsellers
AddNiI/Final_Project_2team_Minimal pull request #4
Opened 2023-12-05 16:55 UTC by AddNiI

2023-12-26 00:12 UTC, marianaD4 reviewed
Не забуваємо про семантичні теги

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +    display: block;
для чого?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +    width: 343px;
використовуємо контейнер

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        color: var(--Blue-font, #0A224A);
використовуємо змінні

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        display: block;
для чого?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        &bl{
не інформативна назва

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +            color: var(--Blue-font, #0A224A);
змінна

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +            display: block;
для чого?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +            &ock{
так не пишемо, формуємо інформативні назви для

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        padding-left: 282px;
padding-left: 282px?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        width: 704px;
використовуємо контейнер

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        display: block;
для чого?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        padding-left: 618px;
padding-left: 618px;?

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +        width: 1096px;
використовуємо контейнер

2023-12-26 00:12 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +                    margin-left: 24px;
використовуємо інформативні назви для блоків та елементів
не розділяємо частини слів

2023-12-26 16:59 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +    display: block;
так треба

2023-12-26 16:59 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +    width: 343px;
?

2023-12-26 16:59 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        color: var(--Blue-font, #0A224A);
?

2023-12-26 17:00 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        display: block;
так треба

2023-12-26 17:00 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        &bl{
?

2023-12-26 17:00 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        width: 704px;
?

2023-12-26 17:00 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        display: block;
так треба!!!!!!!!!!!!!!!!!!

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        padding-left: 618px;
так треба!!!!!!!!!!!!!!!!!!

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +        width: 1096px;
?

2023-12-26 17:01 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +                    margin-left: 24px;
?

2024-01-12 19:18 UTC, marianaD4 requested changes

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +      <h2 class="beatsellers-name">BESTSELLERS</h2>
пишемо всередину контейнера заголовок
зараз не по центру заголовок

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +            <img class="beatsellers-block__image" src="" alt="erore: image not found by this screen or this browser"/>
додаємо src

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
src

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
src

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
src

2024-01-12 19:18 UTC, marianaD4 commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
src

2024-01-12 19:18 UTC, marianaD4 commented on src/images/banner 2x 2.png
файли з пробілами

2024-01-12 19:18 UTC, marianaD4 commented on src/svg/svg1.html
чому розширення html?

2024-01-12 19:18 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +    width: 343px;
використали контейнер
для чого тоді ширина?

2024-01-12 19:18 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +      padding-left: 618px;
переміщаємо заголовок у контейнер і пишемо `text-align: center`

2024-01-12 19:18 UTC, marianaD4 commented on scss/components/_beatsellers.scss
> +      width: 1096px;
для чого? якщо використали контейнер

2024-01-12 19:45 UTC, AddNiI commented on main.html
> +      <h2 class="beatsellers-name">BESTSELLERS</h2>
fixed

2024-01-12 19:46 UTC, AddNiI commented on main.html
> +            <img class="beatsellers-block__image" src="" alt="erore: image not found by this screen or this browser"/>
fixed

2024-01-12 19:46 UTC, AddNiI commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
fixed

2024-01-12 19:46 UTC, AddNiI commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
fixed

2024-01-12 19:46 UTC, AddNiI commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
fixed

2024-01-12 19:47 UTC, AddNiI commented on main.html
> +                <img class="beatsellers-block__simage" src="" alt="erore: image not found by this screen or this browser"/>
fixed

2024-01-12 19:47 UTC, AddNiI commented on src/images/banner 2x 2.png
з цим данило розбирався

2024-01-12 19:47 UTC, AddNiI commented on src/svg/svg1.html
треба було свг а воно html

2024-01-12 19:48 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +      padding-left: 618px;
fixed

2024-01-12 19:48 UTC, AddNiI commented on scss/components/_beatsellers.scss
> +      width: 1096px;
fixed

2024-01-16 12:52 UTC, marianaD4 requested changes
немає  головного зображення на 1440+ 
![image](https://github.com/AddNiI/Final_Project_2team_Minimal/assets/124216656/f337c9f5-78bc-4014-a206-902448cfc2be)
Виправ це і можна мержити

2024-01-16 13:27 UTC, merged