Feat about us
AddNiI/Final_Project_2team_Minimal pull request #6
Opened 2023-12-12 16:36 UTC by AddNiI

2023-12-26 00:18 UTC, marianaD4 requested changes
використовуємо контейнер!!!

2023-12-26 00:18 UTC, marianaD4 commented on main.html
> +        <div class="about-us-name">
допрацьовуємо над назвами класів
не забуваємо про семантику

2023-12-26 00:18 UTC, marianaD4 commented on main.html
> +      </div>
чому усе блоки? де елементи?

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    width: 375px;
використовуємо контейнер

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    width: 375px;
дублювання коду

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    background-color: #f7faff;
викорстовуємо змінні

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    color: #0a224a;
викорстовуємо змінні

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    height: 983px;
не пишемо фіксовану висоту

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    width: 768px;
використовуємо контейнер

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +        width: 704px;
використовуємо контейнер + padding

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +    display: block;
для чого?

2023-12-26 00:18 UTC, marianaD4 commented on SCSS/components/_aboutus.scss
> +      width: 1320px;
використовуємо контейнер

2023-12-26 16:57 UTC, AddNiI commented on main.html
> +      </div>
?

2023-12-26 16:57 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    width: 375px;
?

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    width: 375px;
так треба

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    background-color: #f7faff;
?

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    height: 983px;
?

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    width: 768px;
?

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +        width: 704px;
?

2023-12-26 16:58 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +    display: block;
так треба

2023-12-26 16:59 UTC, AddNiI commented on SCSS/components/_aboutus.scss
> +      width: 1320px;
?

2024-01-12 19:23 UTC, marianaD4 requested changes
додай src і можеш мержити

2024-01-12 19:23 UTC, marianaD4 commented on main.html
> +        <img src="" alt="erore: image not found by this screen or this browser">
src

2024-01-12 19:42 UTC, merged