Feat clients
AddNiI/Final_Project_2team_Minimal pull request #9
Opened 2024-01-04 16:37 UTC by AddNiI

2024-01-09 10:06 UTC, marianaD4 requested changes
використовуємо вкладеність 
https://sass-lang.com/documentation/style-rules/

2024-01-09 10:06 UTC, marianaD4 commented on SCSS/components/_clients.scss
> +  background-color: #f7faff;
виносимо змінну у файл і використовуємо

2024-01-09 10:06 UTC, marianaD4 commented on SCSS/components/_clients.scss
> +  height: 374px;
не використовуємо фіксовану висоту

2024-01-09 10:06 UTC, marianaD4 commented on main.html
> +            <p>
зменшуємо кількість тегів `<p class="clients-reviews__comment">`

2024-01-09 10:06 UTC, marianaD4 commented on main.html
> +            <p>
<p class="clients-reviews__comment">

2024-01-09 10:06 UTC, marianaD4 commented on css/main.css
> +.clients-reviews h2 {
додаємо до h2 клас і викорстовуємо класовий селектор

2024-01-09 10:06 UTC, marianaD4 commented on css/main.css
> +.clients-reviews__comment p {
тільки класові селектори

2024-01-09 10:06 UTC, marianaD4 commented on css/main.css
> +  background-color: #f7faff;
виносимо у змінну

2024-01-09 10:06 UTC, marianaD4 commented on css/main.css
> +  height: 374px;
не використовуємо фіксовану висоту

2024-01-09 10:06 UTC, marianaD4 commented on css/main.css
> +  color: #0a224a;
використовуємо змінні

2024-01-12 19:27 UTC, marianaD4 approved these changes

2024-01-12 19:27 UTC, marianaD4 commented on SCSS/components/_clients.scss
> +}
краще написати `arrows: false` в js

2024-01-16 12:56 UTC, marianaD4 commented
Давай напишемо для каруселі так, щоб не було виходу тексту за межі картки```
$(document).ready(function () {
  $(".clients-reviews__block").slick({
    dots: false,
    infinite: false,
    arrows: false,
    speed: 300,
    slidesToShow: 3,
    slidesToScroll: 3,
    responsive: [
      {
        breakpoint: 1200,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: true
        }
      },
      {
        breakpoint: 376,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
        }
      }
    ]
  });
});

```
Зміни js код і можна мержити

2024-01-16 13:01 UTC, AddNiI commented
> Давай напишемо для каруселі так, щоб не було виходу тексту за межі картки
> 
> ```
> $(document).ready(function () {
>   $(".clients-reviews__block").slick({
>     dots: false,
>     infinite: false,
>     arrows: false,
>     speed: 300,
>     slidesToShow: 3,
>     slidesToScroll: 3,
>     responsive: [
>       {
>         breakpoint: 1200,
>         settings: {
>           slidesToShow: 2,
>           slidesToScroll: 1,
>           infinite: true
>         }
>       },
>       {
>         breakpoint: 376,
>         settings: {
>           slidesToShow: 1,
>           slidesToScroll: 1,
>           infinite: true,
>         }
>       }
>     ]
>   });
> });
> ```
> 
> Зміни js код і можна мержити

де

2024-01-16 13:37 UTC, merged